services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\ConvertimBundle\:
        exclude: '../../{Command,Controller,DependencyInjection,Form,Migrations,Resources,Twig}'
        resource: '../../**/*{Enum,Facade,Factory,Repository,Transformer}.php'

    Shopsys\ConvertimBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']
